#!/usr/bin/env python3

# **********************************************
# * CSVTILEDTOMAP Tool                         *
# * Convert TILED CSV Map to comprehensive     *
# **********************************************


import array, struct, sys, io, os, string, math, json, csv, subprocess,re

# ---------------------
# Constant DEFINES
# ---------------------

PROGRAMNAME = "CSVTiled To Map Tool"
VERSION = "1.0"
COPYRIGHT = "2020"
HEADEROFFSET = 7
PACK = "pack"

TMPFILE = "CSVTiled.TMP"
PACKTMPFILE = TMPFILE + ".pck"

# -----------------------------------------------------------------------------
# Logo, usage and help
# -----------------------------------------------------------------------------

def logo():
    print('%s v%s (c) %s Armando Perez' % (PROGRAMNAME, VERSION, COPYRIGHT))


def usage(execfile):
    print("\nUsage: %s input output\n" % execfile)
    print("     output:     basename output file name")
    print("     map:        csv base raw map data")
    print("     screen:     csv screen data") 
    print("     scr size X: Screen size X")
    print("     scr size Y: Screen size Y")
    print("     compress:   yes / no")
    print("     extra1:     csv extra data (items, enemies...)") 
    print("     ...")
    print("     extrax:     csv extra data (items, enemies...)") 
    print() 



# -----------------------------------------------------------------------------
# File I/O
# -----------------------------------------------------------------------------


def readfile(namefile, header=False, offset=HEADEROFFSET):
    arr = []
    f = open(namefile, 'rb')
    if (header):
        f.seek(offset)
    bytes_read = f.read()
    for b in bytes_read:
        byte = struct.unpack('B', b)
        arr.append(byte[0])
    f.close()
    return arr


def readstringfile(namefile):
    f = open (namefile, 'r')
    string = f.read()
    f.close()
    return string

def readjsonfile(namefile):
    f = open (namefile, 'r')
    data = json.load(f)
    f.close()
    return data

def readcsvfile(namefile, delimiter=","):
    data = []
    with open (namefile, mode = 'r') as csv_file:
        csv_reader = csv.reader (csv_file, delimiter = delimiter)
        for row in csv_reader:
            data.append(row)
    return data

def writefile(namefile, data):
    f = open (namefile,'wb')
    for b in data:
        byte = struct.pack('B',b)
        f.write(byte)
    f.flush()
    f.close()            

        
def writestringfile(namefile, string):
    f = open (namefile, 'wb')
    for b in string:
        f.write(b)
    f.flush()
    f.close()


def basename(namefile):
    return os.path.splitext(namefile)[0]
    

def notdir(namefile):
    return os.path.basename(namefile)

# -----------------------------------------------------------------------------
# String
# -----------------------------------------------------------------------------

def str2bool (boolstr):
    
    if boolstr.lower() in ("yes", "true", "t", "y", "1"):
        return True
    
    return False


def bytetohexstr (byte):
    db = "#"
    if (byte < 0x10):
        db += "0"
    db += "%X" % byte
    return db

# -----------------------------------------------------------------------------
# Array
# -----------------------------------------------------------------------------

def getwindowfromarray (array, wx, wy, idx, sizex):
    
    data = []
    for y in range (0, wy):
        for x in range (0, wx):
            pos = idx + ((sizex * y) + x)
            data.append(array[pos])

    return data



# -----------------------------------------------------------------------------
# CSV
# -----------------------------------------------------------------------------

def csvdicttoraw (csvdict):
    data = []

    for row in csvdict:
        for b in row:
            data.append (int(b))

    return data        




# -----------------------------------------------------------------------------
# Binary and ASM
# -----------------------------------------------------------------------------

def datatodb (data):

    db = ""

    for i in range (0, len(data)):
        if ((i & 7) == 0):
            db += "\t\tDEFB\t" 
        byte = data[i]
        db += "#"
        if (byte < 0x10):
            db += "0"
        db += "%X" % byte
        if (((i & 7) != 7) & (i != len(data) -1)):
            db += ", "
        else:
            db += "\n"

    db += "\n\n"
    return db


def screenstodb (screens, basename, mapsizex, mapsizey, screendata, screensizex, screensizey, compress = False):

    basepad = basename.upper().ljust(8, " ")
    db = ""

    # Title
    db += ";                                       ****************************************\n"
    db += ";                                       * ----- AUTOGENERATED MAP DATA ------- *\n"
    db += ";                                       *               " + basepad + "               *\n"
    db += ";                                       ****************************************\n"
    db += "\n"
    
    db += basename 
    
    # Map data
    sizex = mapsizex / screensizex
    sizey = mapsizey / screensizey


    db += "\t\tDEFB\t"
    db += bytetohexstr(sizex) + ", "
    db += bytetohexstr(sizey)
    db += "\n\n"
    

    # Generate Pointers

    pointers = getmappointers (screens, mapsizex, mapsizey, screendata, screensizex, screensizey)

    db += "\n"
    db += ";\n"
    db += ";\t\t--- SCREEN TABLE POINTERS ---\n"
    db += ";\n"
    db += "\n\n"
    db += ".SCRPT" 

    for y in range (0, sizey):
        db += "\t\tDEFW\t"
        for x in range (0, sizex):
            scr = pointers[x][y] 
            mx = scr[0]
            my = scr[1]

            if (scr[2] == []):
                db += "#0000" 
            else:
                db += ".SP" + str(mx) + str(my)
            if (x < (sizex - 1)):
                db += ", "
        db += "\n"
    db += ".SCRPTE\n"

    # Generate Screen Data

    db += "\n\n"
    db += ";\n"
    db += ";\t\t--- SCREEN DATA ---\n"
    db += ";\n"
    db += "\n\n"

    for row in pointers:
        for scr in row:
            data = scr[2]
            if (data != []):
                mx = scr[0]
                my = scr[1]
                basename = ".SP" + str(mx) + str(my) 
                db += "; ------------------------\n"
                db += "; " + basename + "\n"
                db += "; ------------------------\n\n"
                db += basename

                # screen data
                wx = data[4]
                wy = data[5]

                db += "\t\tDEFB\t" + bytetohexstr(wx) + ", " + bytetohexstr(wy)
                db += "\n"
                db += "\t\tDEFW\t" + basename + "MAP" + "\n"

                # extra pointers

                db += "\n\n"

                # map data 
                if (compress): 
                    sdata = data[1]
                else:
                    sdata = data[0]

                db += "\t\t; MAP DATA"
                if (compress):
                    db += " (PACKED)"
                db += "\n\n"
                db += basename + "MAP\n"
                db += datatodb(sdata)
                db += "\n\n"

    return  db

# -----------------------------------------------------------------------------
# Compress
# -----------------------------------------------------------------------------

def compressdata (data):
    
    cdata = []

    # data to tmp
    writefile (TMPFILE, data)
    
    # compress data with packer
    subprocess.call([PACK, TMPFILE])

    # read file
    cdata = readfile(PACKTMPFILE)

    # delete temporal files
    os.remove(TMPFILE) 
    os.remove(PACKTMPFILE) 

    return cdata




# -----------------------------------------------------------------------------
# Screen Splitter
# -----------------------------------------------------------------------------

def extractscreens (mapdata, mapsizex, mapsizey, splitdata, sizex, sizey, compress = False):

    pos = 0
    x = 0
    y = 0
    screens = []
    while (y < mapsizey):
        if (splitdata[pos] == 0):
            scr, tr, wx, wy = splitscreen(mapdata, mapsizex, mapsizey, splitdata, sizex, sizey, pos)
            cscr = [] 
            if (compress):
                cscr = compressdata(scr)
            screens.append((scr, cscr, x, y, wx, wy)) 
            x = tr % mapsizex
        x = x + 1
        if (x >= mapsizex):
            x = 0
            y = y + 1
        pos = (y * mapsizex) + x
         
    return screens


def splitscreen (mapdata, mapsizex, mapsizey, splitdata, sizex, sizey, pos):
    
    screen = []
    
    tl, tr, bl, br = getscrpositions (mapsizex, mapsizey, splitdata, sizex, sizey, pos)
    wx = (tr - tl) + 1
    wy = ((bl / mapsizex) - (tl / mapsizex)) + 1
    screen = getwindowfromarray(mapdata, wx, wy, tl, mapsizex)

    return screen, tr, wx, wy


def getscrpositions (mapsizex, mapsizey, splitdata, sizex, sizey, pos):

    topleft = pos
    topright = pos
    bottomleft = pos
    bottomright = pos
    
    idx = 0

    # Get top right
    while (idx < mapsizex):
        topright = idx + pos
        if (splitdata[topright] == 1):
            break
        idx = idx + 1

    # Get bottom left 
    idx = 0
    while (idx < mapsizey):
        bottomleft = (idx * mapsizex) + pos
        if (splitdata[bottomleft] == 2):
            break
        idx = idx + 1 

    # Get bottom right
    bottomright = bottomleft + (topright - pos)
    
    return topleft, topright, bottomleft, bottomright


def getmappointers (screens, mapsizex, mapsizey, screendata, screensizex, screensizey):
    
    pointers = []
    sizex = mapsizex / screensizex
    sizey = mapsizey / screensizey

    # Init
    for y in range (0, sizey):
        row = []
        pointers.append(row)
        for x in range (0, sizex):
            scr = [x, y, []]
            row.append(scr)

    for scr in screens:
        # get x, y pointer
        x = scr[2] 
        y = scr[3]
        mx = x / screensizex
        my = y / screensizey

        pointers[mx][my][2] = scr

    return pointers

# -----------------------------------------------------------------------------
# Main program
# -----------------------------------------------------------------------------

def main(args):
    
    logo()
   
    if (len(args) < 3):
        usage(args[0])
        exit (-1)

    outputname = basename(args[1])
    map = args[2]
    
    print("Output Basename: ", notdir(outputname))
    print("Map:  ", map)
    
    tmpoutput = outputname + ".TMP"

    # read csv dictionary

    csvdict = readcsvfile(map)    
    mapsizex = len(csvdict[0])
    mapsizey = len(csvdict)

    print("Map Size X: ", mapsizex)
    print("Map Size Y: ", mapsizey)
   
    # to raw data
    rawdata = csvdicttoraw(csvdict) 

    # write output files
    writefile(outputname + ".MAP", rawdata)
    writestringfile (outputname + ".MAP.Z8A", datatodb(rawdata))


    # Ok, here we have raw data now we need check screen data

    if (len(args) >= 6):
        screencsv = args[3]
        screensizex = int(args[4])
        screensizey = int(args[5])
        compress = str2bool(args[6])
        print("Screen Data: ", screencsv)
        print("Screen Size X: ",screensizex)
        print("Screen Size Y: ",screensizey)
        print("Compress:", compress)
        csvscreen = readcsvfile(screencsv)
        screendata = csvdicttoraw(csvscreen) 
        screens = extractscreens(rawdata, mapsizex, mapsizey, screendata, screensizex, screensizey, compress)
        dbscreens = screenstodb (screens, notdir(outputname), mapsizex, mapsizey, screendata, screensizex, screensizey, compress)
        writestringfile (outputname + ".Z8A", dbscreens)

    # Now check the extras


    #bye
    exit(0)


# ---------------------
# Call to Main
# ---------------------

main(sys.argv)    




