#!/usr/bin/env python3

# **********************************************
# * CSVTILEDTORAW Tool                         *
# * Convert TILED CSV Map to binary RAW        *
# **********************************************


import array, struct, sys, io, os, string, math, json, csv

# ---------------------
# Constant DEFINES
# ---------------------

PROGRAMNAME = "CSVTiled To Raw Tool"
VERSION = "1.0"
COPYRIGHT = "2020"
HEADEROFFSET = 7



# -----------------------------------------------------------------------------
# Logo, usage and help
# -----------------------------------------------------------------------------

def logo():
    print('%s v%s (c) %s Armando Perez' % (PROGRAMNAME, VERSION, COPYRIGHT))


def usage(execfile):
    print("\nUsage: %s input output\n" % execfile)
    print("     input:    Json Tiled File.")
    print("     output:   Binary Raw Data File")
    print("     patmap: (Optional) pattern map")
    print() 



# -----------------------------------------------------------------------------
# File I/O
# -----------------------------------------------------------------------------


def readfile(namefile, header=True, offset=HEADEROFFSET):
    arr = []
    f = open(namefile, 'rb')
    if (header):
        f.seek(offset)
    bytes_read = f.read()
    for b in bytes_read:
        byte = struct.unpack('B', b)
        arr.append(byte[0])
    f.close()
    return arr


def readstringfile(namefile):
    f = open (namefile, 'r')
    string = f.read()
    f.close()
    return string

def readjsonfile(namefile):
    f = open (namefile, 'r')
    data = json.load(f)
    f.close()
    return data

def readcsvfile(namefile, delimiter=","):
    data = []
    with open (namefile, mode = 'r') as csv_file:
        csv_reader = csv.reader (csv_file, delimiter = delimiter)
        for row in csv_reader:
            data.append(row)
    return data

def writefile(namefile, data):
    f = open (namefile,'wb')
    for b in data:
        byte = struct.pack('B',b)
        f.write(byte)
    f.flush()
    f.close()            

        
def writestringfile(namefile, string):
    f = open (namefile, 'wb')
    for b in string:
        f.write(b)
    f.flush()
    f.close()


# -----------------------------------------------------------------------------
# CSV
# -----------------------------------------------------------------------------

def csvdicttoraw (csvdict):
    data = []

    for row in csvdict:
        for b in row:
            it = int(b)
            if (it < 0):
                it = 0
            data.append (it)

    return data        


# -----------------------------------------------------------------------------
# Binary and ASM
# -----------------------------------------------------------------------------

def datatodb (data):

    db = ""

    db += "; Autogenerated  \n\n\n"

    for i in range (0, len(data)):
        if ((i & 7) == 0):
            db += "\tDEFB\t" 
        byte = data[i]
        db += "#"
        if (byte < 0x10):
            db += "0"
        db += "%X" % byte
        if ((i & 7) != 7):
            db += ", "
        else:
            db += "\n"

    db += "\n\n"
    return db



# -----------------------------------------------------------------------------
# MAP
# -----------------------------------------------------------------------------

def rawdatatomap (rawdata, mapdata, sizex, sizey):
    map = [None] * len(rawdata) * 4
        
    for y in range (0, sizey):
        for x in range(0, sizex):
            p = (y * sizex) + x
            v = rawdata[p]
            pm = v * 4
            mp  = ((y << 1) * (sizex << 1)) + (x << 1)
            map[mp] = mapdata[pm] 
            map[mp + 1] = mapdata[pm + 1] 
            map[mp + (sizex << 1)] = mapdata[pm + 2] 
            map[mp + 1 + (sizex << 1)] = mapdata[pm + 3] 

    return map



# -----------------------------------------------------------------------------
# Main program
# -----------------------------------------------------------------------------

def main(args):
    
    logo()
   
    if (len(args) < 3):
        usage(args[0])
        exit (-1)

    inputname = args[1]
    outputname = args[2]
    
    
    print("Input:  ", inputname)
    print("Output: ", outputname)

    # read csv dictionary

    csvdict = readcsvfile(inputname)    
    mapsizex = len(csvdict[0])
    mapsizey = len(csvdict)

    print("Map Size X: ", mapsizex)
    print("Map Size Y: ", mapsizey)
   
    # to raw data
    rawdata = csvdicttoraw(csvdict) 

    # write output files
    writefile(outputname, rawdata)
    writestringfile (outputname + ".Z8A", datatodb(rawdata))

    if (len(args) > 3):
        mapdatafile = args[3]
        print("Map Pattern Data: ", mapdatafile)
        mapdata = readfile(mapdatafile, False)
        rawmapdata = rawdatatomap(rawdata, mapdata, mapsizex, mapsizey)
        writefile(outputname + "_MAP", rawmapdata)
        writestringfile (outputname + "_MAP" + ".Z8A", datatodb(rawmapdata))
        
    #bye
    exit(0)


# ---------------------
# Call to Main
# ---------------------

main(sys.argv)    



