#!/usr/bin/env python3

# **********************************************
# * TILED2RAW Tool                             *
# * Convert TILED JSON Map to binary RAW       *
# **********************************************


import array, struct, sys, io, os, string, math, json

# ---------------------
# Constant DEFINES
# ---------------------

PROGRAMNAME = "TILED2RAW Tool"
VERSION = "1.0"
COPYRIGHT = "2019"
HEADEROFFSET = 7



# -----------------------------------------------------------------------------
# Logo, usage and help
# -----------------------------------------------------------------------------

def logo():
    print('%s v%s (c) %s Ramones' % (PROGRAMNAME, VERSION, COPYRIGHT))


def usage(execfile):
    print("\nUsage: %s input output\n" % execfile)
    print("     input:    Json Tiled File.")
    print("     layer:    Json field key layer name")
    print("     mode:     raw | table")
    print("     output:   Binary Raw Data File")
    print("     sizex:    (table / rawtable mode) size in x patterns per screen")
    print("     sizey:    (table / rawtable mode) size in y patterns per screen")
    print() 

# -----------------------------------------------------------------------------
# File I/O
# -----------------------------------------------------------------------------


def readfile(namefile, header=True, offset=HEADEROFFSET):
    arr = []
    f = open(namefile, 'rb')
    if (header):
        f.seek(offset)
    bytes_read = f.read()
    for b in bytes_read:
        byte = struct.unpack('B', b)
        arr.append(byte[0])
    f.close()
    return arr


def readstringfile(namefile):
    f = open (namefile, 'r')
    string = f.read()
    f.close()
    return string

def readjsonfile(namefile):
    f = open (namefile, 'r')
    data = json.load(f)
    f.close()
    return data


def writefile(namefile, data):
    f = open (namefile,'wb')
    for b in data:
        byte = struct.pack('B',b)
        f.write(byte)
    f.flush()
    f.close()            

        
def writestringfile(namefile, string):
    f = open (namefile, 'wb')
    for b in string:
        f.write(b)
    f.flush()
    f.close()

# -----------------------------------------------------------------------------
# JSON
# -----------------------------------------------------------------------------


def readlayerobject (jsondata, name):

    layers = jsondata["layers"]
    for l in layers:
        if (l["name"] == name):
            return l            
            break

    return {}


def datatodb (data):

    db = ""

    db += "; Autogenerated  \n\n\n"

    for i in range (0, len(data)):
        if ((i & 7) == 0):
            db += "\tDEFB\t" 
        byte = data[i]
        db += "#"
        if (byte < 0x10):
            db += "0"
        db += "%X" % byte
        if ((i & 7) != 7):
            db += ", "
        else:
            db += "\n"

    db += "\n\n"
    return db


# -----------------------------------------------------------------------------
# To Raw
# -----------------------------------------------------------------------------

def toraw (layer, w, h, sx, sy, outputname):


    # pattern - 1
    for i in range(0, len(layer)):
        pat = layer[i]
        if (pat != 0):
            pat = pat - 1
            layer[i] = pat

    db = datatodb (layer)

    # Write file
    writefile (outputname, layer)
    writestringfile (outputname + ".Z8A", db)


# -----------------------------------------------------------------------------
# TO RAWTABLE
# -----------------------------------------------------------------------------

def torawtable (layer, w, h, sx, sy, outputname):
    
    table = []
    x = 0
    y = 0
    print(w)
    print(h)
    for i in range(0, len(layer)):
        pat = layer[i]
        if (pat != 0): 
            pat = pat - 1
            table.append({
                'x': x,
                'y': y,
                'pat': pat
                })
        x = x + 1
        if (x >= w):
            x = 0
            y = y + 1

            
    db = ""

    # Create source file
    # and binary file

    label = os.path.splitext(os.path.basename(outputname))[0]
    
    binary = []
    db = ""
    db += "; Autogenerated  \n\n\n"
    db += "; X Pat \n"
    db += "; Y Pat \n"
    db += "; Pattern \n"
    db += label + "\n\n" 

    for entry in table:
        db += "\t\tDEFB\t" 
        
        xb = entry["x"]
        yb = entry["y"]
        pb = entry["pat"]

        binary.append(xb & 0xFF)
        binary.append(yb & 0xFF)
        binary.append(pb & 0xFF)

        db += "#"
        if (xb < 0x10):
            db += "0"
        db += "%X" % xb
        db += ", "

        db += "#"
        if (yb < 0x10):
            db += "0"
        db += "%X" % yb
        db += ", "

        db += "#"
        if (pb < 0x10):
            db += "0"
        db += "%X" % pb


        db += "\n"

    db += "\n\n"
    db += ".END"
    db += "\n\n"

    writestringfile (outputname, db)

    # Generate .BIN file (binary)
    writefile(outputname + ".BIN", binary)

# -----------------------------------------------------------------------------
# TO TABLE
# -----------------------------------------------------------------------------

def totable (layer, w, h, sx, sy, outputname):

    numscrs = (w / sx) * (h / sy)
    table = []
    scr = 0
    cx = 0
    cy = 0
    xscr = 0
    yscr = 0
    scr = 0
    cnt = 0
    x = 0
    y = 0
    for i in range(0, len(layer)):
        pat = layer[i]
        if (pat != 0): 
            pat = pat - 1
            table.append({
                'idscr': scr,
                'x': x,
                'y': y,
                'xr': xscr,
                'yr': yscr,
                'pat': pat
                })
        
        xscr = xscr + 1
        if (xscr >= sx):
            xscr = 0
        cx = (cx + 1)
        x = x + 1
        if (cx >= w):
            cx = 0
            x = 0
            y = y + 1
            yscr = yscr + 1
 
        if (yscr >= sy):
            cy += (w / sx)
            yscr = 0

        scr = cy + (cx / sx) 

    # SPECIAL ORDER AND DATA FOR NEST

    def byidscr (element):
        return element["idscr"]
   
    # Soft by idscr
    tsorted = sorted(table, key=byidscr)

    # offsets to idscr, counters, and prepared data

    offsets = []
    
    # fill offsets
    for n in range (0, numscrs):
        offsets.append((0,0))

    data = []
    
    # Prepare data
    cnt = 0
    off = 0
    oldid = 0 
    for element in tsorted:
        offsets[oldid] = (cnt, off)

        if (oldid != element["idscr"]):
            oldid = element["idscr"]
            off = off + (cnt << 1)
            cnt = 0

        xy = (((element["xr"] & 0x0F) ) |  ((element["yr"] & 0xF) <<4)) & 0xFF
        data.append(xy)
        data.append(element["pat"])
        cnt = cnt + 1 
        offsets[oldid] = (cnt, off)
    
    # Create source file
    # and binary file

    label = os.path.splitext(os.path.basename(outputname))[0]
    
    binary = []
    db = ""
    db += "; Autogenerated  \n\n\n"
    db += label + "\n\n" 

    db += ".OFFSET" 
    

    for off in offsets:

        word = "{0:#0{1}x}".format(off[0] , 4)[2:]
        word = "#" + word.upper()
        db += "\t\tDEFB\t"
        db += word
        db += "\n"


        word = "{0:#0{1}x}".format(off[1] , 6)[2:]
        word = "#" + word.upper()
        db += "\t\tDEFW\t"
        db += word
        db += "\n"

        binary.append(off[0])
        binary.append(off[1] & 0xFF)
        binary.append(off[1] >> 8)


    db += ".DATA" 
    
    for i in range (0, len(data)):
        if ((i & 7) == 0):
            db += "\t\tDEFB\t" 
        byte = data[i]
        binary.append(byte & 0xFF)
        db += "#"
        if (byte < 0x10):
            db += "0"
        db += "%X" % byte

        if ((i & 7) != 7):
            if (i < len(data) - 1):
                db += ", "
        else:
            db += "\n"

    db += "\n\n"
    db += ".END"
    db += "\n\n"

    writestringfile (outputname, db)

    # Generate .BIN file (binary)
    writefile(outputname + ".BIN", binary)


# -----------------------------------------------------------------------------
# Main program
# -----------------------------------------------------------------------------

def main(args):
    
    logo()
   
    if (len(args) < 5):
        usage(args[0])
        exit (-1)

    filename = args[1]
    layername = args[2]
    mode = args[3]
    outputname = args[4]
    sx = 0
    sy = 0
    if (mode == 'table'):
        sx = int(args[5])
        sy = int(args[6])
    
    print("Input:  ", filename)
    print("Layer:  ", layername)
    print("Mode:   ", mode)
    print("Output: ", outputname)

    # Read JSON file
    jsondata = readjsonfile(filename)   

    # Read Layer and properties
    layer = readlayerobject(jsondata, layername)
    data = layer["data"]
    w = layer["width"]
    h = layer["height"]
    func = mainswitcher(mode) 
    func(data, w, h, sx, sy, outputname) 


    exit(0)

def mainswitcher(case): 
    switcher = {
            'raw': toraw,
            'table': totable,
            'rawtable': torawtable
    }

    func = switcher.get(case, lambda: 'nothing')
    return func




# ---------------------
# Call to Main
# ---------------------

main(sys.argv)    



